name = "audit-github"
prompt = "Actúa como un experto en DevOps y CI/CD y realiza una auditoría sobre los siguientes archivos de configuración de Github. Enfócate en la seguridad, el rendimiento y la escalabilidad. Quiero que busques posibles mejoras y me des un feedback con las mejoras que aplicarías. Los archivos son:"
